### ISSUE TITLE
DESIGN: add possibility to change theme

### ISSUE THREAD

**Issue by bineh** [alexdd/tricktrack#10]
On admin page there should be a possiblity to change the color of our main theme color. perhaps 4 different basiccolors of which the admin can use one, or switch beetween them. (alex wants gets rid of my fancy blue style ;-))

**Comment by bineh** [comment]
please set a new tracker.themecolor attribute do the tracker object, initial value shloud be #447799.

**Comment by alexdd** [comment]
added @themecolor with initial value of "#E6BC5C" (Raw Sienna)

**Comment by bineh** [comment]
please set a new tracker.themecolor attribute do the tracker object, initial value shloud be #447799.

**Comment by alexdd** [comment]
done
