### ISSUE TITLE
SERVER: status codes

### ISSUE THREAD

**Issue by bineh** [alexdd/tricktrack#12]
Please use the correct status codes returned when user is unauthorized or not allowed to access the page. 
http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

After that please asign this issue to bineh, so I can adapt error messages for the user.

**Comment by alexdd** [comment]
replaced 403 with 401 status codes

**Comment by bineh** [comment]
please make "debug: false" work
