### ISSUE TITLE
SERVER: socket.io not properly working

### ISSUE THREAD

**Issue by bineh** [alexdd/tricktrack#25]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:9999/socket.io/?EIO=3&transport=polling&t=1442577486728-13. (Grund: CORS-Anfrage fehlgeschlagen)

**Comment by alexdd** [comment]
Obsolet
